apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zr1zu45vy-python
  janus-idp.io/tekton: zr1zu45vy-python
  backstage.io/kubernetes-id: zr1zu45vy-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zr1zu45vy-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
