apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zr1zu45vy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zr1zu45vy-python 
  name: zr1zu45vy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zr1zu45vy-python 
